# SITE SETUP
# Documentation: https://sourcethemes.com/academic/

# marketing
microsoft_clarity = ""

# Color theme.
#   Choose from `default`, `ocean`, `forest`, `dark`, `apogee`, `1950s`, `coffee`, `cupcake`, `strawberry`.
color_theme = "default"
# Enable users to switch between day and night mode?
day_night = true

# Font style.
#   Choose from `default`, `classic`, or `playfair`.
font = "classic"

# Description for social sharing and search engines. If undefined, superuser role is used in place.
description = ""

# Default image for social sharing and search engines. Place image in `static/img/` folder and specify image name here.
sharing_image = ""

# Twitter username (without @). Used when a visitor shares your site on Twitter.
twitter = ""

# Display a logo in navigation bar rather than title (optional).
#   To enable, place an image in `static/img/` and reference its filename below. To disable, set the value to "".
logo = ""

# Enable global source code highlighting? true/false
# Documentation: https://sourcethemes.com/academic/docs/writing-markdown-latex/#highlighting-options
highlight = true
# highlight_languages = ["r"]  # Add support for highlighting additional languages
# highlight_style = "github"  # For supported styles, see https://cdnjs.com/libraries/highlight.js/

# Enable global LaTeX math rendering?
#   If false, you can enable it locally on a per page basis.
math = false

# Privacy pack
#   Show a cookie consent message to visitors
#   Anonymize IP in Google Analytics (if enabled)
privacy_pack = false

# Date and time format (refer to https://sourcethemes.com/academic/docs/customization/#date-format )
#   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
date_format = "Jan 2, 2006"
#   Examples: "3:04 pm" or "15:04"
time_format = "3:04 PM"

############################
##  Contact Widget setup  ##
############################

# Enter contact details (optional). To hide a field, clear it to "".
email = "jajh@dps.aau.dk"
phone = "+4599408095"
address = "Fibigerstræde 1, 9220 Aalborg Ø"





# Configuration of publication pages.
[publications]
  # Date format (refer to https://sourcethemes.com/academic/docs/customization/#date-format )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "January 2006"

  # Citation style ("apa" or "mla")
  citation_style = "apa"

# Configuration of project pages.
[projects]
  # Views for associated content.
  #   1: List
  #   2: Compact
  #   3: Card
  #   4: Citation (publications only)
  post_view = 3
  publication_view = 3
  talk_view = 2

# Search.
[search]
  # Search provider:
  #   0: No search engine
  #   1: academia (built-in)
  #   2: Algolia (https://www.algolia.com)
  engine = 0

  # Configuration of Algolia search engine.
  # Paste the values from your Algolia dashboard.
  [search.algolia]
    app_id = ""
    api_key = ""
    index_name = ""
    show_logo = false
